"""Sharding must partition the work exactly: no item lost, none duplicated.

Kaggle gives 2x T4, but `device_map="auto"` puts the whole model on ONE card and
leaves the other idle. We therefore run one process per GPU over a slice of the
work. If the slices overlap we pay twice; if they miss items we silently lose
data. Both are invisible at runtime, so they are asserted here.
"""

from __future__ import annotations

import pytest

from csasr.llm import filter_bigrams, gen_bigrams, gen_sentences
from csasr.llm import backend as backend_mod
from csasr.llm.backend import LLMBackend
from csasr.manifest import read_jsonl, write_jsonl


class OneBigramBackend(LLMBackend):
    """Emits a bigram keyed to the prompt so shards produce disjoint output."""

    model_id = "shardstub"

    def _generate(self, convs, sampling):
        out = []
        for conv in convs:
            user = conv[-1]["content"]
            if "language mix bigrams" in user:
                # Key the output to the exemplar text so each call is distinct.
                tag = "".join(c for c in user if c.isdigit())[:6] or "0"
                out.append(f"शब्द{tag} word{tag}")
            elif "direct translations" in user:
                lines = [f"{i+1}: NO" for i, l in enumerate(user.splitlines())
                         if l.strip() and l[0].isdigit()]
                out.append("\n".join(lines))
            elif "Generate four sentences" in user:
                bg = user.rsplit(":", 1)[1].strip()
                hi, en = bg.split()
                out.append(f"मैंने {hi} {en} देखा\nI saw {hi} {en} today")
            else:
                out.append("")
        return out


@pytest.fixture
def stub(monkeypatch):
    for m in (gen_bigrams, filter_bigrams, gen_sentences):
        monkeypatch.setattr(m, "build_backend", lambda name, **kw: OneBigramBackend())
    monkeypatch.setattr(backend_mod, "build_backend", lambda name, **kw: OneBigramBackend())


def _run_sharded(main, tmp_path, out_name, base_args, n_shards):
    rows = []
    for i in range(n_shards):
        out = tmp_path / f"{out_name}.shard{i}.jsonl"
        main([*base_args,
              "--out", str(out),
              "--cache", str(tmp_path / f"c.{out_name}.{i}.jsonl"),
              "--shard", str(i), "--num-shards", str(n_shards)])
        rows += list(read_jsonl(out))
    return rows


class TestGenBigramsSharding:
    def _train(self, tmp_path):
        p = tmp_path / "train.jsonl"
        write_jsonl(p, [{"utt_id": f"u{i}", "text": f"इस spoken tutorial {i} में document"}
                        for i in range(20)])
        return p

    def test_two_shards_equal_one_unsharded_run(self, tmp_path, stub):
        train = self._train(tmp_path)
        base = ["--train-manifest", str(train), "--n-calls", "12", "--batch-size", "4"]

        single = _run_sharded(gen_bigrams.main, tmp_path, "one", base, 1)
        double = _run_sharded(gen_bigrams.main, tmp_path, "two", base, 2)

        assert len(single) == len(double)
        # call_ids must be globally unique and cover every call exactly once.
        ids = sorted(r["call_id"] for r in double)
        assert ids == sorted(r["call_id"] for r in single)
        assert len(set(ids)) == len(ids), "a call was generated by BOTH shards"

    def test_shards_cover_every_call_id(self, tmp_path, stub):
        train = self._train(tmp_path)
        base = ["--train-manifest", str(train), "--n-calls", "10", "--batch-size", "4"]
        rows = _run_sharded(gen_bigrams.main, tmp_path, "cov", base, 3)
        assert {r["call_id"] for r in rows} == set(range(10))


class TestGenSentencesSharding:
    def test_shards_partition_the_bigrams(self, tmp_path, stub):
        bg = tmp_path / "bigrams.jsonl"
        write_jsonl(bg, [
            {"bigram": f"शब्द{i} word{i}", "hi_word": f"शब्द{i}", "en_word": f"word{i}"}
            for i in range(9)
        ])
        base = ["--bigrams", str(bg), "--batch-size", "4"]

        single = _run_sharded(gen_sentences.main, tmp_path, "one", base, 1)
        double = _run_sharded(gen_sentences.main, tmp_path, "two", base, 2)

        assert {r["bigram"] for r in single} == {r["bigram"] for r in double}
        assert len(single) == len(double)
        ids = [r["sent_id"] for r in double]
        assert len(set(ids)) == len(ids), "two shards produced the same sentence"


class TestFilterBigramsSharding:
    def test_shards_partition_the_pairs(self, tmp_path, stub):
        raw = tmp_path / "raw.jsonl"
        write_jsonl(raw, [{"bigram": f"शब्द{i} word{i}", "call_id": i} for i in range(8)])
        base = ["--raw", str(raw), "--items-per-call", "4", "--n-samples", "1"]

        single = _run_sharded(filter_bigrams.main, tmp_path, "one", base, 1)
        double = _run_sharded(filter_bigrams.main, tmp_path, "two", base, 2)

        got_single = {r["bigram"] for r in single}
        got_double = {r["bigram"] for r in double}
        assert got_single == got_double, "sharding changed which bigrams survive"
        assert len(double) == len(got_double), "a pair was checked by BOTH shards"
